In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sns.set_style('darkgrid')
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [3]:
df = pd.read_csv('./train.csv')
#upload data

## Clean Data

In [4]:
df
#take a highlevel look at the data

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500
5,138,535126040,20,RL,137.0,16492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,WD,190000
6,2827,908186070,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2006,New,140000
7,145,535154050,20,RL,NaN,12160,Pave,NaN,IR1,Lvl,...,0,0,NaN,MnPrv,NaN,0,5,2010,COD,142000
8,1942,535353130,20,RL,NaN,15783,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,Shed,400,6,2007,WD,112500
9,1956,535426130,60,RL,70.0,11606,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,9,2007,WD,135000
10,1044,527451290,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2008,COD,85400
11,2752,906380150,20,RL,64.0,7488,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,2,2006,WD,183600
12,807,906226060,70,RL,120.0,26400,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,6,2009,WD,131000
13,1177,533236070,160,FV,24.0,2645,Pave,Pave,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,12,2008,ConLD,200000
14,1480,907418040,20,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2008,WD,193000
15,324,923202105,20,RL,93.0,10114,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,173500
16,1311,902301140,70,RM,34.0,4571,Pave,Grvl,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2008,COD,98000
17,770,905101490,20,RL,80.0,8816,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,6,2009,WD,139000
18,2063,905107140,20,RL,71.0,8197,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,4,2007,WD,143500
19,69,528458070,60,FV,72.0,8640,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,Con,215200
20,2062,905106150,20,RL,109.0,8724,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2007,WD,129000
21,351,527131030,120,RL,40.0,5664,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,10,2009,WD,278000
22,2393,528142010,60,RL,103.0,12867,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,New,344133
23,12,527165230,20,RL,NaN,7980,Pave,NaN,IR1,Lvl,...,0,0,NaN,GdPrv,Shed,500,3,2010,WD,185000
24,2339,527250040,190,RL,100.0,34650,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,1,2006,WD,145000
25,624,535104120,20,RL,92.0,10573,Pave,NaN,IR1,Lvl,...,288,0,NaN,GdPrv,NaN,0,4,2009,WD,187500
26,86,532376160,20,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,NaN,0,4,2010,WD,138500
27,1534,909277040,50,RL,NaN,11700,Pave,Grvl,IR1,HLS,...,0,0,NaN,NaN,NaN,0,7,2008,WD,198000
28,2243,911103060,190,C (all),75.0,8250,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2007,WD,119600
29,1957,535450190,50,RL,60.0,8064,Pave,NaN,Reg,Lvl,...,0,0,NaN,MnPrv,Shed,2000,7,2007,WD,122900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,2810,907410100,60,RL,70.0,8400,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,3,2006,WD,195800
2022,2872,909475020,20,RL,NaN,16381,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,12,2006,WD,223000
2023,1072,528181010,120,RL,135.0,12304,Pave,NaN,IR3,Lvl,...,0,0,NaN,NaN,NaN,0,6,2008,WD,192000
2024,1654,527353080,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2007,WD,197000
2025,2394,528142060,60,RL,82.0,10672,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,11,2006,New,298236
2026,2212,909275110,70,RL,60.0,7230,Pave,NaN,Reg,Lvl,...,153,0,NaN,GdPrv,NaN,0,10,2007,WD,238000
2027,2628,535456010,90,RL,75.0,8512,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,WD,119000
2028,2526,534127190,20,RL,NaN,20781,Pave,NaN,IR2,Lvl,...,0,0,NaN,NaN,NaN,0,6,2006,WD,262500
2029,969,921128050,20,RL,85.0,12633,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,5,2009,WD,425000
2030,306,911202100,50,C (all),66.0,8712,Pave,Pave,Reg,HLS,...,0,0,NaN,NaN,NaN,0,1,2010,WD,102776
2031,25,527402250,20,RL,NaN,12537,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,149900
2032,311,914475090,80,RL,74.0,9620,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdPrv,Shed,80,5,2010,WD,190000
2033,300,909455040,120,RM,35.0,3907,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,3,2010,WD,162500
2034,2775,907175060,20,RL,79.0,9236,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,217000
2035,2862,909279040,30,RL,80.0,11600,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,137500
2036,525,528477070,60,FV,84.0,10603,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2009,WD,270000
2037,2730,905300080,20,RL,100.0,13350,Pave,NaN,IR1,Lvl,...,0,0,NaN,MnPrv,NaN,0,6,2006,WD,142500
2038,1892,534401200,80,RL,80.0,9200,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdPrv,NaN,0,5,2007,WD,161000
2039,2288,923228220,160,RM,21.0,1495,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,5,2007,WD,93900
2040,2728,905225080,50,RL,81.0,15593,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,7,2006,WD,225000
2041,1065,528166120,60,RL,110.0,13688,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2008,WD,412500
2042,2842,909101080,50,RL,45.0,8248,Pave,Grvl,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,9,2006,COD,83000
2043,2011,903227140,70,RM,50.0,6000,Pave,NaN,Reg,Lvl,...,0,0,NaN,GdWo,NaN,0,2,2007,WD,128000
2044,1140,531382090,60,RL,65.0,8453,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2008,WD,182000
2045,1051,528102030,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2008,New,394617
2046,1587,921126030,20,RL,79.0,11449,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,1,2008,WD,298751
2047,785,905377130,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2009,WD,82500
2048,916,909253010,50,RL,57.0,7558,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,3,2009,WD,177000
2049,639,535179160,20,RL,80.0,10400,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,144000
2050,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,WD,189000

In [5]:
df['Garage Qual'].fillna(0, inplace=True)
df['Garage Finish'].fillna(0, inplace=True)
df['Garage Yr Blt'].fillna(0, inplace=True)
df['Garage Cars'].fillna(0, inplace=True)
df['Garage Area'].fillna(0, inplace=True)
df['Garage Qual'].fillna(0, inplace=True)
df['Garage Cond'].fillna(0, inplace=True)
df['Garage Type'].fillna(0, inplace=True)

#investigated and all answered na were because there was nothing there
#process after carefully looking at it was to make all na's into zeros and then cross validate that with the garage area
#the area when na in area seemed to mean that the area was zero. I wanted to keep the data so it is a risk I was willing to
#make

In [6]:
def russiancollusion():
    for i,y in enumerate(df):
        df['MS Zoning'][i] = str(df['MS Zoning'][i])
        
#convert MS Zoning into a string so that it is categorized rather than treaded as a number 
#same done for BsmtFin SF 1

In [7]:
russiancollusion()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
def russiancollusion():
    for i,y in enumerate(df):
        df['BsmtFin SF 1'][i] = float(df['BsmtFin SF 1'][i])

In [9]:
russiancollusion()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
Id                 2051 non-null int64
PID                2051 non-null int64
MS SubClass        2051 non-null int64
MS Zoning          2051 non-null object
Lot Frontage       1721 non-null float64
Lot Area           2051 non-null int64
Street             2051 non-null object
Alley              140 non-null object
Lot Shape          2051 non-null object
Land Contour       2051 non-null object
Utilities          2051 non-null object
Lot Config         2051 non-null object
Land Slope         2051 non-null object
Neighborhood       2051 non-null object
Condition 1        2051 non-null object
Condition 2        2051 non-null object
Bldg Type          2051 non-null object
House Style        2051 non-null object
Overall Qual       2051 non-null int64
Overall Cond       2051 non-null int64
Year Built         2051 non-null int64
Year Remod/Add     2051 non-null int64
Roof Style         2051 non-null object
Roof Matl          2051 non-null object
Exterior 1st       2051 non-null object
Exterior 2nd       2051 non-null object
Mas Vnr Type       2029 non-null object
Mas Vnr Area       2029 non-null float64
Exter Qual         2051 non-null object
Exter Cond         2051 non-null object
Foundation         2051 non-null object
Bsmt Qual          1996 non-null object
Bsmt Cond          1996 non-null object
Bsmt Exposure      1993 non-null object
BsmtFin Type 1     1996 non-null object
BsmtFin SF 1       2050 non-null float64
BsmtFin Type 2     1995 non-null object
BsmtFin SF 2       2050 non-null float64
Bsmt Unf SF        2050 non-null float64
Total Bsmt SF      2050 non-null float64
Heating            2051 non-null object
Heating QC         2051 non-null object
Central Air        2051 non-null object
Electrical         2051 non-null object
1st Flr SF         2051 non-null int64
2nd Flr SF         2051 non-null int64
Low Qual Fin SF    2051 non-null int64
Gr Liv Area        2051 non-null int64
Bsmt Full Bath     2049 non-null float64
Bsmt Half Bath     2049 non-null float64
Full Bath          2051 non-null int64
Half Bath          2051 non-null int64
Bedroom AbvGr      2051 non-null int64
Kitchen AbvGr      2051 non-null int64
Kitchen Qual       2051 non-null object
TotRms AbvGrd      2051 non-null int64
Functional         2051 non-null object
Fireplaces         2051 non-null int64
Fireplace Qu       1051 non-null object
Garage Type        2051 non-null object
Garage Yr Blt      2051 non-null float64
Garage Finish      2051 non-null object
Garage Cars        2051 non-null float64
Garage Area        2051 non-null float64
Garage Qual        2051 non-null object
Garage Cond        2051 non-null object
Paved Drive        2051 non-null object
Wood Deck SF       2051 non-null int64
Open Porch SF      2051 non-null int64
Enclosed Porch     2051 non-null int64
3Ssn Porch         2051 non-null int64
Screen Porch       2051 non-null int64
Pool Area          2051 non-null int64
Pool QC            9 non-null object
Fence              400 non-null object
Misc Feature       65 non-null object
Misc Val           2051 non-null int64
Mo Sold            2051 non-null int64
Yr Sold            2051 non-null int64
Sale Type          2051 non-null object
SalePrice          2051 non-null int64
dtypes: float64(11), int64(28), object(42)
memory usage: 1.3+ MB

In [11]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] == 0: 
            if df['Garage Cond'][i] != 0:
                return df['Garage Area'][i]==df['Garage Area'].median()
            
#Checking that if the area == 0 and then the other details in the garage area aligns with it
#if and when there was an issue replace the area with the median area. seemed like the most optimal one to work with

In [12]:
hellofriends()

In [13]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Qual'][i] == 0:
                return df['Garage Qual'][i] == df['Garage Qual'].mode()
            
            
#repeated this step with all the other features of the garage, if the area was not zero but details were abseent/ zero then
#there was probably an issue and i filled it in with the mode or the median depending on what type. numerical or categorical

In [14]:
hellofriends()

In [15]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Finish'][i] == 0:
                return df['Garage Finish'][i]==df['Garage Finish'].mode()
            
#same as what is above

In [16]:
hellofriends()

In [17]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Yr Blt'][i] == 0:
                return df['Garage Yr Blt'][i]== df['Garage Yr Blt'].median()

In [18]:
hellofriends()

In [19]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Cars'][i] == 0:
                return df['Garage Cars'][i]==df['Garage Cars'].median()

In [20]:
hellofriends()

In [21]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Qual'][i] == 0:
                return df['Garage Qual'][i]==df['Garage Qual'][i].mode()

In [22]:
hellofriends()

In [23]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Cond'][i] == 0:
                return df['Garage Cond'][i]== df['Garage Cond'].mode()

In [24]:
hellofriends()

In [25]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Garage Area'][i] != 0: 
            if df['Garage Type'][i] == 0:
                return df['Garage Type'][i]==df['Garage Type'].mode()

In [26]:
hellofriends()

In [27]:
df['Pool Area'].fillna(0, inplace=True)
df['Pool QC'].fillna(0, inplace=True)
df['Fence'].fillna(0, inplace=True)
df['Misc Feature'].fillna(0, inplace=True)
df['Alley'].fillna(0, inplace=True)
df['Mas Vnr Type'].fillna(0, inplace=True)
df['Mas Vnr Area'].fillna(0, inplace=True)

#investigated and all answered na were because there was none in place for pool

In [28]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Pool Area'][i] != 0: 
            if df['Pool QC'][i] == 0:
                return df['Pool QC'][i]==df['Pool QC'].mode()

In [29]:
hellofriends()

In [30]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Mas Vnr Area'][i] != 0: 
            if df['Mas Vnr Type'][i] == 0:
                return df['Mas Vnr Type'][i] == df['Mas Vnr Type'].mode()

In [31]:
hellofriends()

In [32]:
def hellofriends():
    for i,y in enumerate(df):
        if df['Fireplaces'][i] != 0: 
            if df['Fireplace Qu'][i] == 0:
                return df['Fireplace Qu'][i] == df['Fireplace Qu'][i].mode()

In [33]:
hellofriends()

In [34]:
df['Lot Frontage'].fillna(0, inplace=True)
df['Fireplace Qu'].fillna(0, inplace=True)
#verified and answered na were because there were none in place

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
Id                 2051 non-null int64
PID                2051 non-null int64
MS SubClass        2051 non-null int64
MS Zoning          2051 non-null object
Lot Frontage       2051 non-null float64
Lot Area           2051 non-null int64
Street             2051 non-null object
Alley              2051 non-null object
Lot Shape          2051 non-null object
Land Contour       2051 non-null object
Utilities          2051 non-null object
Lot Config         2051 non-null object
Land Slope         2051 non-null object
Neighborhood       2051 non-null object
Condition 1        2051 non-null object
Condition 2        2051 non-null object
Bldg Type          2051 non-null object
House Style        2051 non-null object
Overall Qual       2051 non-null int64
Overall Cond       2051 non-null int64
Year Built         2051 non-null int64
Year Remod/Add     2051 non-null int64
Roof Style         2051 non-null object
Roof Matl          2051 non-null object
Exterior 1st       2051 non-null object
Exterior 2nd       2051 non-null object
Mas Vnr Type       2051 non-null object
Mas Vnr Area       2051 non-null float64
Exter Qual         2051 non-null object
Exter Cond         2051 non-null object
Foundation         2051 non-null object
Bsmt Qual          1996 non-null object
Bsmt Cond          1996 non-null object
Bsmt Exposure      1993 non-null object
BsmtFin Type 1     1996 non-null object
BsmtFin SF 1       2050 non-null float64
BsmtFin Type 2     1995 non-null object
BsmtFin SF 2       2050 non-null float64
Bsmt Unf SF        2050 non-null float64
Total Bsmt SF      2050 non-null float64
Heating            2051 non-null object
Heating QC         2051 non-null object
Central Air        2051 non-null object
Electrical         2051 non-null object
1st Flr SF         2051 non-null int64
2nd Flr SF         2051 non-null int64
Low Qual Fin SF    2051 non-null int64
Gr Liv Area        2051 non-null int64
Bsmt Full Bath     2049 non-null float64
Bsmt Half Bath     2049 non-null float64
Full Bath          2051 non-null int64
Half Bath          2051 non-null int64
Bedroom AbvGr      2051 non-null int64
Kitchen AbvGr      2051 non-null int64
Kitchen Qual       2051 non-null object
TotRms AbvGrd      2051 non-null int64
Functional         2051 non-null object
Fireplaces         2051 non-null int64
Fireplace Qu       2051 non-null object
Garage Type        2051 non-null object
Garage Yr Blt      2051 non-null float64
Garage Finish      2051 non-null object
Garage Cars        2051 non-null float64
Garage Area        2051 non-null float64
Garage Qual        2051 non-null object
Garage Cond        2051 non-null object
Paved Drive        2051 non-null object
Wood Deck SF       2051 non-null int64
Open Porch SF      2051 non-null int64
Enclosed Porch     2051 non-null int64
3Ssn Porch         2051 non-null int64
Screen Porch       2051 non-null int64
Pool Area          2051 non-null int64
Pool QC            2051 non-null object
Fence              2051 non-null object
Misc Feature       2051 non-null object
Misc Val           2051 non-null int64
Mo Sold            2051 non-null int64
Yr Sold            2051 non-null int64
Sale Type          2051 non-null object
SalePrice          2051 non-null int64
dtypes: float64(11), int64(28), object(42)
memory usage: 1.3+ MB

In [36]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['Bsmt Cond'][i] == 0: 
                return df['Bsmt Cond'][i] == df['Bsmt Cond'].mode()
            #print(df['BsmtFin SF 1'][i], df['Lot Frontage'][i])

In [37]:
hellofriends()

In [38]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['Bsmt Exposure'][i] == 0: 
                return df['Bsmt Exposure'][i] == df['Bsmt Exposure'].mode()
                #return df['Exposure'].median()

In [39]:
hellofriends()

In [40]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['BsmtFin Type 1'][i] == 0: 
                return df['Bsmt Type 1'][i] == df['Bsmt Exposure'][i].mode()

In [41]:
hellofriends()

In [42]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['BsmtFin Type 2'][i] == 0:
                return df['Bsmt Type 2'][i] == df['Bsmt Type 2'].mode()

In [43]:
hellofriends()

In [44]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['Bsmt Unf SF'][i] == 0:
                return df['Bsmt Unf SF'][i]==df['Bsmt Unf SF'].median()

In [45]:
hellofriends()

False

In [46]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] == 0: 
            if df['Bsmt Unf SF'][i] != 0:
                return df['BsmtFin SF 1'][i] == df['BsmtFin SF 1'].median()

In [47]:
hellofriends()

False

In [48]:
def hellofriends():
    for i,y in enumerate(df):
        if df['BsmtFin SF 1'][i] != 0: 
            if df['Total Bsmt SF'][i] == 0:
                return df['Total Bsmt Sf'].median()

In [49]:
hellofriends()

In [50]:
df.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,0.0,13517,Pave,0,IR1,Lvl,...,0,0,0,0,0,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,0,IR1,Lvl,...,0,0,0,0,0,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,0,IR1,Lvl,...,0,0,0,0,0,0,3,2010,WD,138500

In [51]:
import sklearn.metrics as metrics
import sklearn.linear_model as linear_model
import pandas as pd

from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression


%matplotlib

Using matplotlib backend: Qt5Agg

In [52]:
import sklearn.metrics as metrics
import sklearn.linear_model as linear_model
import pandas as pd

from matplotlib.pyplot import *


%matplotlib

from sklearn.linear_model import LinearRegression

model = LinearRegression()

Using matplotlib backend: Qt5Agg

In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split, KFold, cross_val_score

%matplotlib inline

In [54]:
df2 = pd.read_csv('./test.csv')

In [55]:
np.unique(df2['Overall Qual'])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [56]:
df2.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [57]:
df2['Garage Qual'].fillna(0, inplace=True)
df2['Garage Finish'].fillna(0, inplace=True)
df2['Garage Yr Blt'].fillna(0, inplace=True)
df2['Garage Cars'].fillna(0, inplace=True)
df2['Garage Area'].fillna(0, inplace=True)
df2['Garage Qual'].fillna(0, inplace=True)
df2['Garage Cond'].fillna(0, inplace=True)
df2['Garage Type'].fillna(0, inplace=True)

In [58]:
def russiancollusion():
    for i,y in enumerate(df2):
        df2['MS SubClass'][i] = str(df2['MS SubClass'][i])
        
#convert ms subclass to a string

In [59]:
russiancollusion()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [60]:
def russiancollusion():
    for i,y in enumerate(df2):
        df2['BsmtFin SF 1'][i] = float(df2['BsmtFin SF 1'][i])
        
#convert bsmtfin sf 1 to a float

In [61]:
russiancollusion()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [62]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] == 0: 
            if df2['Garage Cond'][i] != 0:
                return df2['Garage Area'][i]==df2['Garage Area'].median()
            
#check that where garage area is zero, garage condition is aligned. so that we are able to tell if an area was missing and 
#fill in as the median because that is the best potential data to fill it in with

In [63]:
hellofriends()

In [64]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Qual'][i] == 0:
                return df2['Garage Qual'][i]==df2['Garage Qual'].mode()
            
##checked garage area. if area did not equal zero but quality was zero fill in with mode. this was done for info below an if 
#this was numeric data for the examples we used the median. it was a piece of data that would not do too much damage

In [65]:
hellofriends()

In [66]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Finish'][i] == 0:
                return df2['Garage Finish'][i]==df2['Garage Finish'].mode()

In [67]:
hellofriends()

In [68]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Yr Blt'][i] == 0:
                return df2['Garage Yr Blt'][i]==df2['Garage Yr Blt'].median()

In [69]:
hellofriends()

In [70]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Cars'][i] == 0:
                return df2['Garage Cars'][i]==df2['Garage Cars'].median()

In [71]:
hellofriends()

In [72]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Qual'][i] == 0:
                return df2['Garage Qual'][i]==df2['Garage Qual'].mode()

In [73]:
hellofriends()

In [74]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Cond'][i] == 0:
                return df2['Garage Cond'][i]==df2['Garage Cond'].mode()

In [75]:
hellofriends()

In [76]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Garage Area'][i] != 0: 
            if df2['Garage Type'][i] == 0:
                return df2['Garage Type'][i]==df2['Garage Type'].mode()

In [77]:
hellofriends()

In [78]:
df2['Pool Area'].fillna(0, inplace=True)
df2['Pool QC'].fillna(0, inplace=True)
df2['Fence'].fillna(0, inplace=True)
df2['Misc Feature'].fillna(0, inplace=True)
df2['Alley'].fillna(0, inplace=True)
df2['Mas Vnr Type'].fillna(0, inplace=True)
df2['Mas Vnr Area'].fillna(0, inplace=True)

In [79]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Pool Area'][i] != 0: 
            if df2['Pool QC'][i] == 0:
                return df2['Pool QC'][i]==df2['Pool QC'].mode()
            
##checked pool area. if area did not equal zero but quality was zero fill in with mode. this was done for info below an if 
#this was numeric data for the examples we used the median. it was a piece of data that would not do too much damage

In [80]:
hellofriends()

In [81]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Mas Vnr Area'][i] != 0: 
            if df2['Mas Vnr Type'][i] == 0:
                return df2['Mas Vnr Type'][i]==df2['Mas Vnr Type'].mode()

In [82]:
hellofriends()

In [83]:
df2['Lot Frontage'].fillna(0, inplace=True)
df2['Fireplace Qu'].fillna(0, inplace=True)

In [84]:
def hellofriends():
    for i,y in enumerate(df2):
        if df2['Fireplaces'][i] != 0: 
            if df2['Fireplace Qu'][i] == 0:
                return df2['Fireplace Qu'][i]==df2['Fireplace Qu'].mode()

In [85]:
hellofriends()

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
Id                 2051 non-null int64
PID                2051 non-null int64
MS SubClass        2051 non-null int64
MS Zoning          2051 non-null object
Lot Frontage       2051 non-null float64
Lot Area           2051 non-null int64
Street             2051 non-null object
Alley              2051 non-null object
Lot Shape          2051 non-null object
Land Contour       2051 non-null object
Utilities          2051 non-null object
Lot Config         2051 non-null object
Land Slope         2051 non-null object
Neighborhood       2051 non-null object
Condition 1        2051 non-null object
Condition 2        2051 non-null object
Bldg Type          2051 non-null object
House Style        2051 non-null object
Overall Qual       2051 non-null int64
Overall Cond       2051 non-null int64
Year Built         2051 non-null int64
Year Remod/Add     2051 non-null int64
Roof Style         2051 non-null object
Roof Matl          2051 non-null object
Exterior 1st       2051 non-null object
Exterior 2nd       2051 non-null object
Mas Vnr Type       2051 non-null object
Mas Vnr Area       2051 non-null float64
Exter Qual         2051 non-null object
Exter Cond         2051 non-null object
Foundation         2051 non-null object
Bsmt Qual          1996 non-null object
Bsmt Cond          1996 non-null object
Bsmt Exposure      1993 non-null object
BsmtFin Type 1     1996 non-null object
BsmtFin SF 1       2050 non-null float64
BsmtFin Type 2     1995 non-null object
BsmtFin SF 2       2050 non-null float64
Bsmt Unf SF        2050 non-null float64
Total Bsmt SF      2050 non-null float64
Heating            2051 non-null object
Heating QC         2051 non-null object
Central Air        2051 non-null object
Electrical         2051 non-null object
1st Flr SF         2051 non-null int64
2nd Flr SF         2051 non-null int64
Low Qual Fin SF    2051 non-null int64
Gr Liv Area        2051 non-null int64
Bsmt Full Bath     2049 non-null float64
Bsmt Half Bath     2049 non-null float64
Full Bath          2051 non-null int64
Half Bath          2051 non-null int64
Bedroom AbvGr      2051 non-null int64
Kitchen AbvGr      2051 non-null int64
Kitchen Qual       2051 non-null object
TotRms AbvGrd      2051 non-null int64
Functional         2051 non-null object
Fireplaces         2051 non-null int64
Fireplace Qu       2051 non-null object
Garage Type        2051 non-null object
Garage Yr Blt      2051 non-null float64
Garage Finish      2051 non-null object
Garage Cars        2051 non-null float64
Garage Area        2051 non-null float64
Garage Qual        2051 non-null object
Garage Cond        2051 non-null object
Paved Drive        2051 non-null object
Wood Deck SF       2051 non-null int64
Open Porch SF      2051 non-null int64
Enclosed Porch     2051 non-null int64
3Ssn Porch         2051 non-null int64
Screen Porch       2051 non-null int64
Pool Area          2051 non-null int64
Pool QC            2051 non-null object
Fence              2051 non-null object
Misc Feature       2051 non-null object
Misc Val           2051 non-null int64
Mo Sold            2051 non-null int64
Yr Sold            2051 non-null int64
Sale Type          2051 non-null object
SalePrice          2051 non-null int64
dtypes: float64(11), int64(28), object(42)
memory usage: 1.3+ MB

In [87]:
#make certain data categorical below. subclass, garage yr blt, mo sold, zoning, mas vnr type

In [88]:
df['MS SubClass'] = pd.Categorical(df['MS SubClass'])

In [89]:
df2['Garage Yr Blt'] = pd.Categorical(df2['Garage Yr Blt'])

In [90]:
df['Garage Yr Blt'] = pd.Categorical(df['Garage Yr Blt'])

In [91]:
df2['MS SubClass'] = pd.Categorical(df2['MS SubClass'])

In [92]:
df['Mo Sold'] = pd.Categorical(df['Mo Sold'])

In [93]:
df2['Mo Sold'] = pd.Categorical(df2['Mo Sold'])

In [94]:
df['MS Zoning'] = pd.Categorical(df['MS Zoning'])

In [95]:
df2['MS Zoning'] = pd.Categorical(df2['MS Zoning'])

In [96]:
df['Mas Vnr Type'] = pd.Categorical(df['Mas Vnr Type'])

In [97]:
df2['Mas Vnr Type'] = pd.Categorical(df2['Mas Vnr Type'])

In [98]:
df['Bsmt Qual'] = pd.Categorical(df['Bsmt Qual'])

In [99]:
df2['Bsmt Qual'] = pd.Categorical(df2['Bsmt Qual'])

In [100]:
df['Bsmt Cond'] = pd.Categorical(df['Bsmt Cond'])

In [101]:
df2['Bsmt Cond'] = pd.Categorical(df2['Bsmt Cond'])

In [102]:
df['Bsmt Exposure'] = pd.Categorical(df['Bsmt Exposure'])

In [103]:
df2['Bsmt Exposure'] = pd.Categorical(df2['Bsmt Exposure'])

In [104]:
df['BsmtFin Type 1'] = pd.Categorical(df['BsmtFin Type 1'])

In [105]:
df2['BsmtFin Type 1'] = pd.Categorical(df2['BsmtFin Type 1'])

In [106]:
df['BsmtFin Type 2'] = pd.Categorical(df['BsmtFin Type 2'])

In [107]:
df2['BsmtFin Type 2'] = pd.Categorical(df2['BsmtFin Type 2'])

In [108]:
df['Fireplace Qu'] = pd.Categorical(df['Fireplace Qu'])

In [109]:
df2['Fireplace Qu'] = pd.Categorical(df2['Fireplace Qu'])

In [110]:
df['Garage Type'] = pd.Categorical(df['Garage Type'])

In [111]:
df2['Garage Type'] = pd.Categorical(df2['Garage Type'])

In [112]:
df['Garage Finish'] = pd.Categorical(df['Garage Finish'])

In [113]:
df2['Garage Finish'] = pd.Categorical(df2['Garage Finish'])

In [114]:
df['Garage Qual'] = pd.Categorical(df['Garage Qual'])

In [115]:
df2['Garage Qual'] = pd.Categorical(df2['Garage Qual'])

In [116]:
df['Garage Cond'] = pd.Categorical(df['Garage Cond'])

In [117]:
df2['Garage Cond'] = pd.Categorical(df2['Garage Cond'])

In [118]:
df['Pool QC'] = pd.Categorical(df['Pool QC'])

In [119]:
df2['Pool QC'] = pd.Categorical(df2['Pool QC'])

In [120]:
df3 = pd.get_dummies(df[['MS Zoning', 'MS SubClass', 'Neighborhood', 'Foundation', 'Heating', 'Kitchen Qual', 'Bldg Type', 'Central Air', 'Electrical', 'Sale Type', 'Mo Sold']], drop_first=True)
#make dummy variables.
#create new data frame df3 that is with data from the original dataframe
#do the same for dataframe 2 for the testing

In [121]:
df3.shape

(2051, 88)

## Get Dummy Variables

In [122]:
df4 = pd.get_dummies(df2[['MS Zoning', 'MS SubClass', 'Neighborhood', 'Foundation', 'Heating', 'Kitchen Qual', 'Bldg Type', 'Central Air', 'Electrical', 'Sale Type', 'Mo Sold']], drop_first=True)

In [123]:
df4.drop(['Heating_GasA', 'Kitchen Qual_Po', 'Sale Type_VWD'], axis=1, inplace=True)
#getting rid of columns that were in the test data but not in the original data. reasoning is that our model no matter what
#will not be able to compensate for it. because my data did not compensate for it in training, no matter what it should not
#be able to predict it

In [124]:
df3.shape

(2051, 88)

In [125]:
df4.shape
#validate that they are the same size so they can be tested properly. they were not

(879, 81)

In [126]:
#add columns to testing data that were in other data. need to keep things consistent. so I was able to add the new ones in place

In [127]:
missing_cols = set(df3.columns) - set(df4.columns)

## Took care of Excess columns / missing columns

In [128]:
missing_cols

{'Electrical_Mix',
 'Heating_OthW',
 'Heating_Wall',
 'MS SubClass_150',
 'MS Zoning_C (all)',
 'Neighborhood_GrnHill',
 'Neighborhood_Landmrk'}

In [129]:
for c in missing_cols: 
    df4[c] = 0
    
df4 = df4[df3.columns]

In [130]:
print(df3.shape, df4.shape)

(2051, 88) (879, 88)

In [131]:
df4.head()

,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,MS SubClass_30,MS SubClass_40,MS SubClass_45,MS SubClass_50,...,Mo Sold_3,Mo Sold_4,Mo Sold_5,Mo Sold_6,Mo Sold_7,Mo Sold_8,Mo Sold_9,Mo Sold_10,Mo Sold_11,Mo Sold_12
0,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [132]:
missing_cols2 = set(df4.columns) - set(df3.columns)

In [133]:
missing_cols2

set()

In [134]:
df5 = pd.concat([df, df3], axis=1)

In [135]:
df6 = pd.concat([df2, df4], axis=1)

In [136]:
print(df5.shape, df6.shape)
#shape is consistent so good to go

(2051, 169) (879, 168)

In [137]:
#removed              'Sale Type_WD' because the function would not work with it

In [138]:
features2 = ['MS Zoning_C (all)',
             'MS Zoning_FV',
             'MS Zoning_I (all)',
             'MS Zoning_RH',
             'MS Zoning_RL', 
             'MS Zoning_RM',
             'MS SubClass_30',
             'MS SubClass_40',
             'MS SubClass_45', 
             'MS SubClass_50',
             'MS SubClass_60', 
             'MS SubClass_70', 
             'MS SubClass_75', 
             'MS SubClass_80', 
             'MS SubClass_85', 
             'MS SubClass_90', 
             'MS SubClass_120',
             'MS SubClass_150', 
             'MS SubClass_160', 
             'MS SubClass_180', 
             'MS SubClass_190', 
             'Neighborhood_Blueste', 
             'Neighborhood_BrDale', 
             'Neighborhood_BrkSide', 
             'Neighborhood_ClearCr', 
             'Neighborhood_CollgCr', 
             'Neighborhood_Crawfor', 
             'Neighborhood_Edwards',
             'Neighborhood_Gilbert', 
             'Neighborhood_Greens',
             'Neighborhood_GrnHill',
             'Neighborhood_IDOTRR',
             'Neighborhood_Landmrk',
             'Neighborhood_MeadowV', 
             'Neighborhood_Mitchel', 
             'Neighborhood_NAmes', 
             'Neighborhood_NPkVill', 
             'Neighborhood_NWAmes',
             'Neighborhood_NoRidge', 
             'Neighborhood_NridgHt', 
             'Neighborhood_OldTown', 
             'Neighborhood_SWISU', 
             'Neighborhood_Sawyer',
             'Neighborhood_SawyerW', 
             'Neighborhood_Somerst', 
             'Neighborhood_StoneBr', 
             'Neighborhood_Timber', 
             'Neighborhood_Veenker', 
             'Foundation_CBlock',
             'Foundation_PConc', 
             'Foundation_Slab', 
             'Foundation_Stone',
             'Foundation_Wood', 
             'Heating_GasW', 
             'Heating_Grav', 
             'Heating_OthW', 
             'Heating_Wall', 
             'Kitchen Qual_Fa', 
             'Kitchen Qual_Gd',
             'Kitchen Qual_TA',
             'Bldg Type_2fmCon',
             'Bldg Type_Duplex',
             'Bldg Type_Twnhs', 
             'Bldg Type_TwnhsE',
             'Central Air_Y',
             'Electrical_FuseF',
             'Electrical_FuseP',
             'Electrical_Mix',
             'Electrical_SBrkr',  
             'Sale Type_CWD', 
             'Sale Type_Con', 
             'Sale Type_ConLD', 
             'Sale Type_ConLI',
             'Sale Type_ConLw', 
             'Sale Type_New', 
             'Sale Type_Oth', 
             'Mo Sold_2', 
             'Mo Sold_3', 
             'Mo Sold_4', 
             'Mo Sold_5', 
             'Mo Sold_6', 
             'Mo Sold_7', 
             'Mo Sold_8', 
             'Mo Sold_9', 
             'Mo Sold_10', 
             'Mo Sold_11', 
             'Mo Sold_12']

#name all the columns properly so that i can anylize it better later

In [139]:
features = ['Year Built', 'Overall Qual', '1st Flr SF', '2nd Flr SF', 'Full Bath', 'Yr Sold', 'Fireplaces', 'Lot Area']
#create a features list

In [140]:
target = 'SalePrice'
#create a target of saleprice

In [141]:
from sklearn.preprocessing import StandardScaler

In [142]:
#import features list and cal it a new dataframe to keep consistent and not lose some things
df9 = df5[features]

In [143]:
df10 = df6[features]

In [144]:
print(df9.shape, df10.shape)

(2051, 8) (879, 8)

In [149]:
df11=df5[features2]

In [150]:
df12=df6[features2]

In [151]:
print(df11.shape, df12.shape)

(2051, 87) (879, 87)

## Standardize Numerical Data

In [152]:
#standardize variables. for df5 and df6

scaler = StandardScaler()
scaler.fit(df6[features])
df8= scaler.transform(df6[features])

In [153]:
scaler = StandardScaler()
scaler.fit(df5[features])
scaler.mean_
df7= scaler.transform(df5[features])

In [154]:
df7 = np.nan_to_num(df7)

In [155]:
df8 = np.nan_to_num(df8)

In [156]:
df8 = pd.DataFrame(data=df8)

In [157]:
df7 = pd.DataFrame(data=df7)

In [158]:
print(df7.shape, df8.shape)

(2051, 8) (879, 8)

In [159]:
#rename column names for df7 and df8
df7 = df7.rename(columns = {0:'Year Built', 1:'Overall Qual', 2:'1st Flr SF', 3:'2nd Flr SF', 4:'Full Bath', 5: 'Yr Sold', 6:'Fireplaces', 7: 'Lot Area' })

In [160]:
df7

,Year Built,Overall Qual,1st Flr SF,2nd Flr SF,Full Bath,Yr Sold,Fireplaces,Lot Area
0,0.142227,-0.078644,-1.108838,0.997894,0.769779,1.695731,-0.925701,0.512071
1,0.805126,0.622656,-0.634510,2.067055,0.769779,0.933358,0.640811,0.211664
2,-0.620106,-0.779944,-0.271195,-0.773859,-1.051232,1.695731,-0.925701,-0.317944
3,1.136575,-0.779944,-1.060900,0.871004,0.769779,1.695731,-0.925701,-0.039047
4,-2.376787,-0.078644,-0.841397,0.668921,0.769779,1.695731,-0.925701,0.618586
5,-0.189222,-0.078644,1.825436,-0.773859,0.769779,1.695731,0.640811,0.953410
6,1.103430,-0.078644,-0.233349,-0.773859,0.769779,-1.353760,-0.925701,-0.947983
7,-0.421236,-0.779944,0.059321,-0.773859,-1.051232,1.695731,-0.925701,0.310761
8,-0.653251,-0.779944,-0.606756,-0.773859,-1.051232,-0.591387,-0.925701,0.848231
9,-0.089787,-0.779944,-0.314086,1.669938,-1.051232,-0.591387,2.207324,0.228575
10,-0.023497,-0.078644,-1.719409,0.410443,-1.051232,0.170986,-0.925701,-1.243940
11,1.103430,0.622656,0.109782,-0.773859,0.769779,-1.353760,-0.925701,-0.382327
12,-3.039685,-0.779944,0.311623,0.936799,-1.051232,0.933358,0.640811,2.423256
13,0.904561,1.323956,-0.510882,0.741765,0.769779,0.170986,-0.925701,-1.100783
14,1.169720,0.622656,0.495804,-0.773859,0.769779,0.170986,-0.925701,-0.065008
15,1.070285,-0.779944,0.669892,-0.773859,0.769779,1.695731,-0.925701,0.007238
16,-1.846468,-0.779944,-1.363663,0.918000,-1.051232,0.170986,-0.925701,-0.815062
17,-0.288657,-0.779944,-0.109721,-0.773859,-1.051232,0.933358,-0.925701,-0.185319
18,0.175372,-0.078644,0.304054,-0.773859,-1.051232,-0.591387,0.640811,-0.277147
19,1.236010,0.622656,-1.010440,1.066038,0.769779,1.695731,-0.925701,-0.211429
20,-0.122932,-0.779944,-0.682447,-0.773859,-1.051232,-0.591387,0.640811,-0.198967
21,0.937706,1.323956,1.247664,-0.773859,0.769779,0.933358,0.640811,-0.652916
22,1.103430,1.323956,0.112305,1.679337,0.769779,-1.353760,0.640811,0.415644
23,0.672546,-0.078644,0.056798,-0.773859,0.769779,1.695731,-0.925701,-0.309339
24,-0.553816,-0.779944,-0.273718,-0.773859,-1.051232,-1.353760,-0.925701,3.647138
25,-0.354946,-0.078644,0.727922,-0.773859,0.769779,0.933358,0.640811,0.075331
26,-0.222367,-0.779944,-0.682447,-0.773859,-1.051232,1.695731,0.640811,-0.239615
27,-1.150425,-0.779944,0.253594,0.807560,0.769779,0.170986,0.640811,0.242520
28,-2.542511,-0.779944,-0.329224,1.474904,0.769779,-0.591387,-0.925701,-0.269285
29,-0.752686,-0.779944,-1.242558,-0.181708,-1.051232,-0.591387,0.640811,-0.296878
...,...,...,...,...,...,...,...,...
2021,1.103430,0.622656,-0.959979,1.169429,0.769779,-1.353760,-0.925701,-0.247033
2022,-0.089787,-0.078644,1.714423,-0.773859,0.769779,-1.353760,0.640811,0.936944
2023,1.103430,0.622656,0.510942,-0.773859,0.769779,0.170986,0.640811,0.332123
2024,0.241662,0.622656,-0.314086,0.835757,0.769779,-0.591387,0.640811,0.225312
2025,1.136575,1.323956,-0.278764,2.363130,0.769779,-1.353760,0.640811,0.090017
2026,-1.481874,0.622656,-0.750569,1.225825,0.769779,-0.591387,0.640811,-0.420601
2027,-0.388091,-0.779944,0.987793,-0.773859,0.769779,-1.353760,-0.925701,-0.230417
2028,-0.122932,0.622656,2.501605,-0.773859,0.769779,-1.353760,0.640811,1.589681
2029,1.169720,2.025257,2.052508,-0.773859,0.769779,0.933358,0.640811,0.380930
2030,-2.376787,-1.481245,-0.770753,-0.024271,-1.051232,1.695731,-0.925701,-0.200748
2031,-0.023497,-0.779944,-0.218211,-0.773859,-1.051232,1.695731,0.640811,0.366689
2032,0.175372,-0.078644,0.304054,-0.773859,0.769779,1.695731,0.640811,-0.066046
2033,0.573111,1.323956,0.066890,-0.773859,0.769779,1.695731,0.640811,-0.913566
2034,0.838271,-0.078644,0.831366,-0.773859,0.769779,-1.353760,-0.925701,-0.123012
2035,-1.647599,-1.481245,0.039137,-0.773859,-1.051232,-1.353760,0.640811,0.227685
2036,1.136575,1.323956,-0.644602,1.308068,0.769779,0.933358,0.640811,0.079781
2037,0.075938,-0.779944,-0.682447,-0.773859,-1.051232,-1.353760,0.640811,0.487297
2038,-0.222367,-0.078644,-0.309040,-0.773859,0.769779,-0.591387,-0.925701,-0.128353
2039,-0.056642,-1.481245,-1.560458,0.509134,-1.051232,-0.591387,-0.925701,-1.271385
2040,-0.620106,0.622656,0.351992,1.535999,0.769779,-1.353760,0.640811,0.820044
2041,1.037140,2.025257,1.028161,1.801527,0.769779,0.170986,2.207324,0.537439
2042,-1.647599,-1.481245,-0.505836,-0.773859,-1.051232,-1.353760,0.640811,-0.269582
2043,-1.084135,-0.078644,-1.404031,0.692419,-1.051232,-0.591387,2.207324,-0.603071
2044,0.771981,-0.078644,-1.035670,1.235224,0.769779,0.170986,-0.925701,-0.239170
2045,1.202865,1.323956,1.936449,-0.773859,0.769779,0.170986,0.640811,0.352892
2046,1.169720,1.323956,1.421752,-0.773859,0.769779,0.170986,0.640811,0.205285
2047,-1.050990,-1.481245,-0.765707,-0.773859,-1.051232,0.933358,-0.925701,0.337761
2048,-1.448729,-0.078644,0.018953,0.967346,-1.051232,0.933358,0.640811,-0.371943
2049,-0.520671,-1.481245,0.089597,-0.773859,-1.051232,0.933358,2.207324,0.049666
2050,0.904561,0.622656,-0.344362,1.049589,0.769779,1.695731,0.640811,-0.380547

In [161]:
df8 = df8.rename(columns = {0:'Year Built', 1:'Overall Qual', 2:'1st Flr SF', 3:'2nd Flr SF', 4:'Full Bath', 5: 'Yr Sold', 6:'Fireplaces', 7: 'Lot Area' })

## Bring Data Together dummies and numerical that is standardized

In [246]:
#merge dummy variables and standardized variables
df13 = pd.concat([df7, df11], axis=1)

In [247]:
df14 = pd.concat([df8, df12], axis=1)

In [271]:
df13.head()

,Year Built,Overall Qual,1st Flr SF,2nd Flr SF,Full Bath,Yr Sold,Fireplaces,Lot Area,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,MS SubClass_30,MS SubClass_40,MS SubClass_45,MS SubClass_50,MS SubClass_60,MS SubClass_70,MS SubClass_75,MS SubClass_80,MS SubClass_85,MS SubClass_90,MS SubClass_120,MS SubClass_150,MS SubClass_160,MS SubClass_180,MS SubClass_190,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_Greens,Neighborhood_GrnHill,Neighborhood_IDOTRR,Neighborhood_Landmrk,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Kitchen Qual_Fa,Kitchen Qual_Gd,Kitchen Qual_TA,Bldg Type_2fmCon,Bldg Type_Duplex,Bldg Type_Twnhs,Bldg Type_TwnhsE,Central Air_Y,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Mo Sold_2,Mo Sold_3,Mo Sold_4,Mo Sold_5,Mo Sold_6,Mo Sold_7,Mo Sold_8,Mo Sold_9,Mo Sold_10,Mo Sold_11,Mo Sold_12
0,0.142227,-0.078644,-1.108838,0.997894,0.769779,1.695731,-0.925701,0.512071,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,0.805126,0.622656,-0.634510,2.067055,0.769779,0.933358,0.640811,0.211664,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,-0.620106,-0.779944,-0.271195,-0.773859,-1.051232,1.695731,-0.925701,-0.317944,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1.136575,-0.779944,-1.060900,0.871004,0.769779,1.695731,-0.925701,-0.039047,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,-2.376787,-0.078644,-0.841397,0.668921,0.769779,1.695731,-0.925701,0.618586,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [270]:
df14.head()

,Year Built,Overall Qual,1st Flr SF,2nd Flr SF,Full Bath,Yr Sold,Fireplaces,Lot Area,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,MS SubClass_30,MS SubClass_40,MS SubClass_45,MS SubClass_50,MS SubClass_60,MS SubClass_70,MS SubClass_75,MS SubClass_80,MS SubClass_85,MS SubClass_90,MS SubClass_120,MS SubClass_150,MS SubClass_160,MS SubClass_180,MS SubClass_190,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_Greens,Neighborhood_GrnHill,Neighborhood_IDOTRR,Neighborhood_Landmrk,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Kitchen Qual_Fa,Kitchen Qual_Gd,Kitchen Qual_TA,Bldg Type_2fmCon,Bldg Type_Duplex,Bldg Type_Twnhs,Bldg Type_TwnhsE,Central Air_Y,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Sale Type_CWD,Sale Type_Con,Sale Type_ConLD,Sale Type_ConLI,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Mo Sold_2,Mo Sold_3,Mo Sold_4,Mo Sold_5,Mo Sold_6,Mo Sold_7,Mo Sold_8,Mo Sold_9,Mo Sold_10,Mo Sold_11,Mo Sold_12
0,-1.992138,-0.039744,-0.630383,1.543113,0.817846,-1.375505,-0.925183,-0.119395,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,0.212808,-0.767560,2.150564,-0.805235,0.817846,-1.375505,-0.925183,-0.067611,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,1.167188,0.688072,-1.271130,1.110281,0.817846,-1.375505,0.569736,0.673505,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,-1.564313,-0.767560,-0.472823,-0.805235,-0.965992,-0.621721,-0.925183,-0.181337,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,-0.247927,-0.039744,0.645859,-0.805235,-0.965992,0.885846,2.064656,-0.083744,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [248]:
print(df13.shape, df14.shape)

(2051, 95) (879, 95)

In [249]:
print(df8.shape, df11.shape)

(879, 8) (2051, 87)

In [250]:
print(df11.shape, df12.shape)

(2051, 87) (879, 87)

In [251]:
print(df13.shape, df14.shape)

(2051, 95) (879, 95)

In [252]:
X = df13

In [253]:
df5 = df5

In [254]:
y= df5['SalePrice']

## Train test split and create model

In [255]:
#set up training size
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = .9)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [256]:
#allows me to view extra columns to make better judgements and see some things
pd.options.display.max_columns = 100
pd.options.display.max_rows=100

In [257]:
from sklearn.linear_model import ElasticNet, ElasticNetCV
#import data

In [258]:
#determine optimal alpha and fit the ne wmodel called enet_model which is an elastic split

enet_alphas = np.arange(.00001, 20, .1)
enet_ratio = 0.5
enet_model = ElasticNetCV(alphas=enet_alphas, l1_ratio=enet_ratio, cv=5)
enet_model = enet_model.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

In [259]:
enet_optimal_alpha = enet_model.alpha_
enet_optimal_alpha

1e-05

In [260]:
#print intercept
enet_model.intercept_

191844.48928856858

In [261]:
enet_model.coef_

array([ 1.25876416e+04,  1.97096759e+04,  2.34626413e+04,  1.93855881e+04,
       -1.86562797e+02, -1.88360373e+01,  5.14024420e+03,  7.58951673e+03,
        3.68823353e+04,  4.54397838e+04,  3.85975473e+04,  5.28868649e+04,
        4.15154719e+04,  3.95092008e+04,  5.46711733e+03,  4.46658437e+03,
        3.07388984e+03,  1.13543283e+02, -7.99270890e+03, -1.26292218e+03,
        1.69212710e+04, -6.27007101e+03,  4.92006384e+03, -2.59694516e+04,
       -2.62179752e+04,  0.00000000e+00, -3.73362258e+04, -9.19270439e+03,
       -3.01006780e+04,  1.12320636e+04,  1.17415602e+04, -7.19276835e+03,
        2.39115434e+03, -7.34602213e+03,  9.20707860e+03, -1.80455472e+04,
       -1.81448357e+04,  1.48329431e+04,  7.25863263e+04, -1.41091598e+04,
        2.25075602e+03,  9.07307581e+03, -4.11618481e+03, -7.36329086e+03,
        1.13424849e+04, -1.24396180e+04,  3.68762732e+04,  3.78152863e+04,
       -1.44877743e+04, -1.93738737e+04, -7.44158296e+03, -1.26858567e+04,
        4.46239899e+03,  5.53517695e+04,  2.94557332e+03,  4.96396233e+03,
       -6.32406481e+02,  5.78430469e+03, -1.63655835e+04,  1.80121416e+04,
        1.57602096e+04, -3.71560574e+03, -2.18510370e+04, -4.37537501e+04,
        2.78143746e+04, -5.51583320e+04, -4.84940679e+04, -5.42161737e+04,
        2.58318198e+04,  7.69437790e+03, -5.42436900e+03, -2.22870916e+03,
        4.77623539e+03,  1.93807505e+02,  2.80824339e+02, -3.48907963e+04,
        2.30554837e+03, -8.35174465e+03,  4.04784685e+04,  7.72346883e+03,
        1.40678251e+03, -1.61552155e+04,  1.16003600e+04,  1.32692469e+04,
       -6.21894129e+03, -7.44519255e+03, -5.60733079e+03,  5.36475946e+01,
       -5.87231212e+03, -1.67370985e+03, -7.03950900e+03, -5.15415489e+03,
       -1.05715767e+04, -8.14449989e+03, -5.52650458e+03])

In [262]:
coeficients = pd.DataFrame(data = enet_model.coef_)

In [263]:
coeficients.rename(columns={0: 'optimal_elasticnet_coefs'}, inplace=True)

In [268]:
df15=list(df13)

In [265]:
df15 = pd.DataFrame(data=df15)

In [266]:
df16 = pd.concat([df15, coeficients], axis=1)

In [273]:
df19=list(df14)

In [274]:
df20 = pd.DataFrame(data=df19)

In [279]:
df21 = pd.concat([df20, coeficients], axis=1)

In [280]:
df21

                       0  optimal_elasticnet_coefs
0             Year Built              12587.641561
1           Overall Qual              19709.675944
2             1st Flr SF              23462.641305
3             2nd Flr SF              19385.588116
4              Full Bath               -186.562797
5                Yr Sold                -18.836037
6             Fireplaces               5140.244196
7               Lot Area               7589.516728
8      MS Zoning_C (all)              36882.335287
9           MS Zoning_FV              45439.783817
10     MS Zoning_I (all)              38597.547276
11          MS Zoning_RH              52886.864874
12          MS Zoning_RL              41515.471926
13          MS Zoning_RM              39509.200773
14        MS SubClass_30               5467.117325
15        MS SubClass_40               4466.584374
16        MS SubClass_45               3073.889840
17        MS SubClass_50                113.543283
18        MS SubClass_60              -7992.708899
19        MS SubClass_70              -1262.922176
20        MS SubClass_75              16921.270990
21        MS SubClass_80              -6270.071011
22        MS SubClass_85               4920.063843
23        MS SubClass_90             -25969.451565
24       MS SubClass_120             -26217.975176
25       MS SubClass_150                  0.000000
26       MS SubClass_160             -37336.225843
27       MS SubClass_180              -9192.704390
28       MS SubClass_190             -30100.677972
29  Neighborhood_Blueste              11232.063562
30   Neighborhood_BrDale              11741.560245
31  Neighborhood_BrkSide              -7192.768346
32  Neighborhood_ClearCr               2391.154341
33  Neighborhood_CollgCr              -7346.022130
34  Neighborhood_Crawfor               9207.078602
35  Neighborhood_Edwards             -18045.547153
36  Neighborhood_Gilbert             -18144.835679
37   Neighborhood_Greens              14832.943059
38  Neighborhood_GrnHill              72586.326348
39   Neighborhood_IDOTRR             -14109.159842
40  Neighborhood_Landmrk               2250.756020
41  Neighborhood_MeadowV               9073.075809
42  Neighborhood_Mitchel              -4116.184815
43    Neighborhood_NAmes              -7363.290862
44  Neighborhood_NPkVill              11342.484864
45   Neighborhood_NWAmes             -12439.618038
46  Neighborhood_NoRidge              36876.273199
47  Neighborhood_NridgHt              37815.286281
48  Neighborhood_OldTown             -14487.774322
49    Neighborhood_SWISU             -19373.873667
50   Neighborhood_Sawyer              -7441.582962
51  Neighborhood_SawyerW             -12685.856651
52  Neighborhood_Somerst               4462.398994
53  Neighborhood_StoneBr              55351.769493
54   Neighborhood_Timber               2945.573322
55  Neighborhood_Veenker               4963.962329
56     Foundation_CBlock               -632.406481
57      Foundation_PConc               5784.304692
58       Foundation_Slab             -16365.583533
59      Foundation_Stone              18012.141617
60       Foundation_Wood              15760.209563
61          Heating_GasW              -3715.605738
62          Heating_Grav             -21851.037045
63          Heating_OthW             -43753.750092
64          Heating_Wall              27814.374595
65       Kitchen Qual_Fa             -55158.332015
66       Kitchen Qual_Gd             -48494.067919
67       Kitchen Qual_TA             -54216.173722
68      Bldg Type_2fmCon              25831.819789
69      Bldg Type_Duplex               7694.377901
70       Bldg Type_Twnhs              -5424.369001
71      Bldg Type_TwnhsE              -2228.709158
72         Central Air_Y               4776.235386
73      Electrical_FuseF                193.807505
74      Electrical_FuseP                280.824339
75        Electrical_Mix             -34890.796290
76      Electrical_SBrkr               2305.548372
77         Sale Type_CWD              -8351.744648
78         Sale Type_Con              40478.468535
79       Sale Type_ConLD               7723.468831
80       Sale Type_ConLI               1406.782511
81       Sale Type_ConLw             -16155.215539
82         Sale Type_New              11600.360015
83         Sale Type_Oth              13269.246909
84             Mo Sold_2              -6218.941288
85             Mo Sold_3              -7445.192548
86             Mo Sold_4              -5607.330786
87             Mo Sold_5                 53.647595
88             Mo Sold_6              -5872.312122
89             Mo Sold_7              -1673.709852
90             Mo Sold_8              -7039.509003
91             Mo Sold_9              -5154.154888
92            Mo Sold_10             -10571.576715
93            Mo Sold_11              -8144.499889
94            Mo Sold_12              -5526.504582

In [232]:
enet_opt = ElasticNet(alpha=enet_optimal_alpha)

In [233]:
cross_val_score(enet_opt, X_train, y_train, cv=5).mean()
#training data r-squared score

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

0.8158277754431996

In [191]:
print('r-squared of ElasticNet train: ', cross_val_score(enet_opt, X_test, y_test, cv=5).mean())
#rsquared score on eleasctic net

r-squared of ElasticNet train:  0.8305261775661071

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

In [285]:
X_2 = df14
#rename data for using in the model prediction

In [287]:
Pred_Price = enet_model.predict(X_2)
submission = pd.DataFrame({'Id': df2['Id'], 'SalePrice': enet_model.predict(X_2)})

In [288]:
submission['SalePrice'] = round(submission['SalePrice'], 2)
submission.to_csv('HarryConnelly2.csv', index= False)

In [291]:
variable =enet_model.predict(X_train)

In [296]:
variable=pd.DataFrame(data=variable)

In [297]:
pd.concat([variable, y_train], axis=1)

                  0  SalePrice
0     144940.641571   130500.0
1     150898.954023   220000.0
2     178561.155118   109000.0
3      98783.690800   174000.0
4     245824.741321   138500.0
5     174436.285749   190000.0
6     317468.195341   140000.0
7     222640.621365   142000.0
8     270061.075630        NaN
9     165916.586335   135000.0
10    102656.791694    85400.0
11    171636.687775        NaN
12    128800.395682   131000.0
13    206318.904834   200000.0
14    101333.750203   193000.0
15    208427.700662   173500.0
16    190008.560135    98000.0
17     83134.376747   139000.0
18    191351.267793   143500.0
19    154410.859996   215200.0
20    237579.663473   129000.0
21    136113.490482        NaN
22     82297.968689   344133.0
23    230848.660841   185000.0
24    268323.238237   145000.0
25    120384.876341   187500.0
26    104907.511444   138500.0
27     90846.092410   198000.0
28    326009.646021   119600.0
29    122088.605241   122900.0
30    127227.150084   278000.0
31    296104.911544   230000.0
32    119839.601261   270000.0
33     73579.300949   125000.0
34    112038.023327        NaN
35    178356.157853   113500.0
36    229082.500396   127000.0
37    107332.061534   190000.0
38    153518.991795        NaN
39    159042.153502   146000.0
40    134576.500887   147500.0
41    105277.777499   465000.0
42    253910.064007   165500.0
43    134291.419923   131500.0
44    378330.382208   129500.0
45    154497.008033   257076.0
46    192080.731948        NaN
47    162530.886935   149000.0
48    167860.456799   128000.0
49     87586.091047   155000.0
...             ...        ...
1996            NaN   107000.0
1997            NaN   192500.0
1998            NaN   215000.0
1999            NaN   144100.0
2000            NaN   127500.0
2001            NaN   225000.0
2002            NaN   372402.0
2003            NaN   144000.0
2004            NaN   176500.0
2005            NaN   112000.0
2006            NaN   100000.0
2007            NaN    88000.0
2008            NaN   136905.0
2009            NaN    97500.0
2010            NaN    51689.0
2011            NaN   142000.0
2013            NaN   243500.0
2014            NaN   184500.0
2015            NaN   210000.0
2016            NaN   129000.0
2018            NaN   181000.0
2019            NaN   167000.0
2021            NaN   195800.0
2022            NaN   223000.0
2023            NaN   192000.0
2024            NaN   197000.0
2025            NaN   298236.0
2026            NaN   238000.0
2027            NaN   119000.0
2028            NaN   262500.0
2029            NaN   425000.0
2030            NaN   102776.0
2031            NaN   149900.0
2033            NaN   162500.0
2034            NaN   217000.0
2035            NaN   137500.0
2036            NaN   270000.0
2037            NaN   142500.0
2038            NaN   161000.0
2039            NaN    93900.0
2040            NaN   225000.0
2041            NaN   412500.0
2042            NaN    83000.0
2043            NaN   128000.0
2044            NaN   182000.0
2045            NaN   394617.0
2046            NaN   298751.0
2047            NaN    82500.0
2049            NaN   144000.0
2050            NaN   189000.0

[2032 rows x 2 columns]

In [293]:
y_train

454     147110
1270    100000
92      184000
1484    114504
676     255000
Name: SalePrice, dtype: int64